/*
 * Copiright (C) 2019 Santiago León O.
 */

#define GDK_MODIFIERS_TABLE                              \
  GDK_MODIFIERS_ROW(GDK_SHIFT_MASK)                      \
  GDK_MODIFIERS_ROW(GDK_LOCK_MASK)                       \
  GDK_MODIFIERS_ROW(GDK_CONTROL_MASK)                    \
  GDK_MODIFIERS_ROW(GDK_MOD1_MASK)                       \
  GDK_MODIFIERS_ROW(GDK_MOD2_MASK)                       \
  GDK_MODIFIERS_ROW(GDK_MOD3_MASK)                       \
  GDK_MODIFIERS_ROW(GDK_MOD4_MASK)                       \
  GDK_MODIFIERS_ROW(GDK_MOD5_MASK)                       \
  GDK_MODIFIERS_ROW(GDK_BUTTON1_MASK)                    \
  GDK_MODIFIERS_ROW(GDK_BUTTON2_MASK)                    \
  GDK_MODIFIERS_ROW(GDK_BUTTON3_MASK)                    \
  GDK_MODIFIERS_ROW(GDK_BUTTON4_MASK)                    \
  GDK_MODIFIERS_ROW(GDK_BUTTON5_MASK)                    \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_13_MASK)       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_14_MASK)       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_15_MASK)       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_16_MASK)       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_17_MASK)       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_18_MASK)       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_19_MASK)       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_20_MASK)       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_21_MASK)       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_22_MASK)       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_23_MASK)       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_24_MASK)       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_25_MASK)       \
  GDK_MODIFIERS_ROW(GDK_SUPER_MASK)                      \
  GDK_MODIFIERS_ROW(GDK_HYPER_MASK)                      \
  GDK_MODIFIERS_ROW(GDK_META_MASK)                       \
  GDK_MODIFIERS_ROW(GDK_MODIFIER_RESERVED_29_MASK)       \
  GDK_MODIFIERS_ROW(GDK_RELEASE_MASK)
  
char *gdk_modifier_names[32] = {0};

void gdk_modifier_names_init ()
{
#define GDK_MODIFIERS_ROW(name) \
    gdk_modifier_names[bit_pos(name)] = #name;
    GDK_MODIFIERS_TABLE
#undef GDK_MODIFIERS_ROW
}

